apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  replicas: {{ .Values.minio.replicaCount }}
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: "{{ .Values.minio.image }}:{{ .Values.minio.imageTag }}"
          ports:
            - containerPort: {{ .Values.minio.ports.api }}
            - containerPort: {{ .Values.minio.ports.console }}
          env:
            - name: MINIO_ROOT_USER
              value: "{{ .Values.minio.rootUser }}"
            - name: MINIO_ROOT_PASSWORD
              value: "{{ .Values.minio.rootPassword }}"
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc
