apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  ports:
    - name: http-api
      port: {{ .Values.minio.ports.api }}
      targetPort: {{ .Values.minio.ports.api }}
    - name: console
      port: {{ .Values.minio.ports.console }}
      targetPort: {{ .Values.minio.ports.console }}
  selector:
    app: minio
  type: {{ .Values.minio.service.nodetype }}
