apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
data:
  flink-conf.yaml: |
    jobmanager.rpc.address: jobmanager
    taskmanager.numberOfTaskSlots: {{ .Values.flinkConfig.taskmanager.numberOfTaskSlots }}
