apiVersion: v1
kind: Service
metadata:
  name: jobmanager-rpc
  labels:
    app: flink
    component: jobmanager
spec:
  type: {{ .Values.jobmanager.service.type }}
  ports:
  - name: jobmanager-rpc
    port: 6123
    protocol: TCP
    targetPort: 6123
  - name: blobserver
    port: 6124
    protocol: TCP
    targetPort: 6124    
  type: ClusterIP 
  selector:
    app: flink
    component: jobmanager

