apiVersion: v1
kind: Service
metadata:
  name: jobmanager
  labels:
    app: flink
    component: jobmanager
spec:
  type: {{ .Values.jobmanager.service.type }}
  ports:
  - port: {{ .Values.jobmanager.service.port }}
    targetPort: 8081
  type: LoadBalancer
  selector:
    app: flink
    component: jobmanager

