apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager
  labels:
    app: flink
spec:
  replicas: {{ .Values.taskmanager.replicas }}
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}      
      containers:
      - name: taskmanager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: "AWS_ACCESS_KEY_ID"
          value: {{ .Values.environement.AWS_ACCESS_KEY_ID}}
        - name: "AWS_SECRET_ACCESS_KEY"
          value: {{ .Values.environement.AWS_SECRET_ACCESS_KEY}}
        - name: "AWS_REGION"
          value: {{ .Values.environement.AWS_REGION}}          
        ports:
        - containerPort: 6121
        - containerPort: 6122
      volumes:
      - name: flink-config-volume
        configMap:
          name: flink-config
      volumeMounts:
      - mountPath: /opt/flink/conf
        name: flink-config-volume

