apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc
  labels:
    app: mc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc
  template:
    metadata:
      labels:
        app: mc
    spec:
      containers:
        - name: mc
          image: "{{ .Values.mc.image }}:{{ .Values.mc.imageTag }}"
          command: ["/bin/sh", "-c", "until /usr/bin/mc config host add minio http://minio:9000 admin password; do echo '...waiting...' && sleep 1; done;/usr/bin/mc rm -r --force minio/warehouse; /usr/bin/mc mb minio/warehouse;tail -f /dev/null"]  
          env:
            - name: MINIO_ROOT_USER
              value: "{{ .Values.minio.rootUser }}"
            - name: MINIO_ROOT_PASSWORD
              value: "{{ .Values.minio.rootPassword }}"
      initContainers:
        - name: wait-for-minio
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              until nslookup minio; do echo "Waiting for MinIO..."; sleep 1; done
          restartPolicy: Always
